### ISSUE TITLE
Seurat  is not there https://www.scrna-tools.org/tools.html#Seurat

### ISSUE THREAD

**Issue by deo999** [Oshlack/scRNA-tools#23]
which is best clustering tool you will suggest for single-cell methods from  scRNA-tools, i am very new in this so please suggest some.

Thanks

**Comment by lazappi** [comment]
Hi @deo999 

Your question does not seem related to the title. I have checked at the entry for Seurat is available at that link. You will need to follow the link to the Seurat GitHub repository (https://github.com/satijalab/seurat) or website (https://satijalab.org/seurat/) to find the tool itself.

We do not recommend specific tools on the scRNA-tools website instead we provide links to where you can find out more about them (papers and websites) and information that may indicate how popular they are in the community (citations and GitHub stars). If you are new to the field I suggest you read some of the recent review papers and work through some tutorials for the tools you are interested in to get a better understanding of how they work and what would be appropriate for your dataset.
